@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.kawaiicakes.nobullship.multiblock.screen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;