modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/kawaiicakes/NoBullship/issues"

[[mods]]
modId="nobullship"
version="1.19.2-1.0.1"
displayName="No Bullship!"
displayURL="https://github.com/kawaiicakes/NoBullship/"
logoFile="nobullship.png"
credits="I would like to thank blackbirdantlion, embeddedt, and 1whohears!"
authors="kawaiicakes"
description='''
Highly-configurable data-driven crafting recipes using multiblocks.
'''

[[dependencies.nobullship]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nobullship]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
