package io.github.kawaiicakes.nobullship;

import net.minecraftforge.common.ForgeConfigSpec;

public class Config {
    public static ForgeConfigSpec CONFIG;

    public static ForgeConfigSpec.DoubleValue COOLDOWN, DROP_RAW_PERCENT;
    public static ForgeConfigSpec.BooleanValue AUTO_RECIPE, DISABLE_DROP, DROP_RAW;

    static {
        ForgeConfigSpec.Builder builder = new ForgeConfigSpec.Builder();
        builder.push("No Bullship!");

        COOLDOWN = builder
                .comment("The time in seconds that schematics become unusable after use.")
                .translation("config.nobullship.cooldown")
                .comment("Default 1.0 seconds.")
                .defineInRange("cooldown", 1.0, 0.50, 30);

        DROP_RAW_PERCENT = builder
                .comment("The percentage of blocks that will be dropped if an entity is destroyed.")
                .comment("Ignored if raw_drops is disabled.")
                .translation("config.nobullship.raw_drops_percent")
                .comment("Default 67%.")
                .defineInRange("raw_drops_percent", 0.67, 0, 1.00);

        AUTO_RECIPE = builder
                .comment("Whether schematic recipes are autogenerated for multiblock recipes.")
                .comment("Autogenerated recipes have a shaped component of the normal crafting recipe.")
                .translation("config.nobullship.auto_recipe")
                .comment("Default false.")
                .define("auto_recipe", false);

        DISABLE_DROP = builder
                .comment("Whether entities with a multiblock recipe may drop as an item.")
                .translation("config.nobullship.default_drops")
                .comment("Default true.")
                .define("default_drops", true);

        DROP_RAW = builder
                .comment("Whether entities with a multiblock recipe drop a portion of the raw ingredients needed to make them.")
                .translation("config.nobullship.raw_drops")
                .comment("Default true.")
                .define("raw_drops", true);
    }
}
